"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright © 2026 Sintela Ltd. All rights reserved.
Sintela Confidential

common contains the objects that are used in the public API and
the public recording formats.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _TimeseriesDataType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TimeseriesDataTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TimeseriesDataType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TIMESERIES_DATA_TYPE_UNSPECIFIED: _TimeseriesDataType.ValueType  # 0
    TIMESERIES_DATA_TYPE_PHASE: _TimeseriesDataType.ValueType  # 1
    TIMESERIES_DATA_TYPE_PHASE_DIFFERENCE: _TimeseriesDataType.ValueType  # 2
    TIMESERIES_DATA_TYPE_PHASE_RATE: _TimeseriesDataType.ValueType  # 3
    TIMESERIES_DATA_TYPE_STRAIN: _TimeseriesDataType.ValueType  # 4
    TIMESERIES_DATA_TYPE_STRAIN_RATE: _TimeseriesDataType.ValueType  # 5

class TimeseriesDataType(_TimeseriesDataType, metaclass=_TimeseriesDataTypeEnumTypeWrapper):
    """Protobuf specification for Onyx Data Packets."""

TIMESERIES_DATA_TYPE_UNSPECIFIED: TimeseriesDataType.ValueType  # 0
TIMESERIES_DATA_TYPE_PHASE: TimeseriesDataType.ValueType  # 1
TIMESERIES_DATA_TYPE_PHASE_DIFFERENCE: TimeseriesDataType.ValueType  # 2
TIMESERIES_DATA_TYPE_PHASE_RATE: TimeseriesDataType.ValueType  # 3
TIMESERIES_DATA_TYPE_STRAIN: TimeseriesDataType.ValueType  # 4
TIMESERIES_DATA_TYPE_STRAIN_RATE: TimeseriesDataType.ValueType  # 5
Global___TimeseriesDataType: _TypeAlias = TimeseriesDataType  # noqa: Y015

class _DemodDataType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DemodDataTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DemodDataType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DEMOD_DATA_TYPE_UNSPECIFIED: _DemodDataType.ValueType  # 0
    DEMOD_DATA_TYPE_H_SPATIAL_DIFF: _DemodDataType.ValueType  # 1
    DEMOD_DATA_TYPE_H_TEMPORAL_DIFF: _DemodDataType.ValueType  # 2
    DEMOD_DATA_TYPE_V_SPATIAL_DIFF: _DemodDataType.ValueType  # 3
    DEMOD_DATA_TYPE_V_TEMPORAL_DIFF: _DemodDataType.ValueType  # 4
    DEMOD_DATA_TYPE_POLAR_SUM: _DemodDataType.ValueType  # 5
    DEMOD_DATA_TYPE_STACKED: _DemodDataType.ValueType  # 6
    DEMOD_DATA_TYPE_DDC0_RAW: _DemodDataType.ValueType  # 7
    DEMOD_DATA_TYPE_DDC1_RAW: _DemodDataType.ValueType  # 8
    DEMOD_DATA_TYPE_DIFFED_PHASE: _DemodDataType.ValueType  # 9
    DEMOD_DATA_TYPE_ACTUAL_PHASE: _DemodDataType.ValueType  # 10
    DEMOD_DATA_TYPE_OTDR: _DemodDataType.ValueType  # 11
    DEMOD_DATA_TYPE_FPGA_HDR: _DemodDataType.ValueType  # 12
    DEMOD_DATA_TYPE_STACKED_1_OVER_F: _DemodDataType.ValueType  # 13
    DEMOD_DATA_TYPE_FILTERED_ACTUAL_PHASE: _DemodDataType.ValueType  # 14
    DEMOD_DATA_TYPE_GPU_8: _DemodDataType.ValueType  # 15
    DEMOD_DATA_TYPE_GPU_8_PLUS: _DemodDataType.ValueType  # 16

class DemodDataType(_DemodDataType, metaclass=_DemodDataTypeEnumTypeWrapper): ...

DEMOD_DATA_TYPE_UNSPECIFIED: DemodDataType.ValueType  # 0
DEMOD_DATA_TYPE_H_SPATIAL_DIFF: DemodDataType.ValueType  # 1
DEMOD_DATA_TYPE_H_TEMPORAL_DIFF: DemodDataType.ValueType  # 2
DEMOD_DATA_TYPE_V_SPATIAL_DIFF: DemodDataType.ValueType  # 3
DEMOD_DATA_TYPE_V_TEMPORAL_DIFF: DemodDataType.ValueType  # 4
DEMOD_DATA_TYPE_POLAR_SUM: DemodDataType.ValueType  # 5
DEMOD_DATA_TYPE_STACKED: DemodDataType.ValueType  # 6
DEMOD_DATA_TYPE_DDC0_RAW: DemodDataType.ValueType  # 7
DEMOD_DATA_TYPE_DDC1_RAW: DemodDataType.ValueType  # 8
DEMOD_DATA_TYPE_DIFFED_PHASE: DemodDataType.ValueType  # 9
DEMOD_DATA_TYPE_ACTUAL_PHASE: DemodDataType.ValueType  # 10
DEMOD_DATA_TYPE_OTDR: DemodDataType.ValueType  # 11
DEMOD_DATA_TYPE_FPGA_HDR: DemodDataType.ValueType  # 12
DEMOD_DATA_TYPE_STACKED_1_OVER_F: DemodDataType.ValueType  # 13
DEMOD_DATA_TYPE_FILTERED_ACTUAL_PHASE: DemodDataType.ValueType  # 14
DEMOD_DATA_TYPE_GPU_8: DemodDataType.ValueType  # 15
DEMOD_DATA_TYPE_GPU_8_PLUS: DemodDataType.ValueType  # 16
Global___DemodDataType: _TypeAlias = DemodDataType  # noqa: Y015

class _AveragingType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AveragingTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AveragingType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    AVERAGING_TYPE_UNSPECIFIED: _AveragingType.ValueType  # 0
    AVERAGING_TYPE_NONE: _AveragingType.ValueType  # 1
    AVERAGING_TYPE_MAX_RETAINED: _AveragingType.ValueType  # 2
    AVERAGING_TYPE_MEAN: _AveragingType.ValueType  # 3
    AVERAGING_TYPE_MIN_RETAINED: _AveragingType.ValueType  # 4

class AveragingType(_AveragingType, metaclass=_AveragingTypeEnumTypeWrapper): ...

AVERAGING_TYPE_UNSPECIFIED: AveragingType.ValueType  # 0
AVERAGING_TYPE_NONE: AveragingType.ValueType  # 1
AVERAGING_TYPE_MAX_RETAINED: AveragingType.ValueType  # 2
AVERAGING_TYPE_MEAN: AveragingType.ValueType  # 3
AVERAGING_TYPE_MIN_RETAINED: AveragingType.ValueType  # 4
Global___AveragingType: _TypeAlias = AveragingType  # noqa: Y015

class _TriggerInterfaceType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TriggerInterfaceTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TriggerInterfaceType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TRIGGER_INTERFACE_TYPE_UNSPECIFIED: _TriggerInterfaceType.ValueType  # 0
    TRIGGER_INTERFACE_TYPE_SEISMIC: _TriggerInterfaceType.ValueType  # 1
    TRIGGER_INTERFACE_TYPE_AXLE_COUNTER: _TriggerInterfaceType.ValueType  # 2
    TRIGGER_INTERFACE_TYPE_ETHERNET: _TriggerInterfaceType.ValueType  # 3
    TRIGGER_INTERFACE_TYPE_ONBOARD: _TriggerInterfaceType.ValueType  # 4

class TriggerInterfaceType(_TriggerInterfaceType, metaclass=_TriggerInterfaceTypeEnumTypeWrapper): ...

TRIGGER_INTERFACE_TYPE_UNSPECIFIED: TriggerInterfaceType.ValueType  # 0
TRIGGER_INTERFACE_TYPE_SEISMIC: TriggerInterfaceType.ValueType  # 1
TRIGGER_INTERFACE_TYPE_AXLE_COUNTER: TriggerInterfaceType.ValueType  # 2
TRIGGER_INTERFACE_TYPE_ETHERNET: TriggerInterfaceType.ValueType  # 3
TRIGGER_INTERFACE_TYPE_ONBOARD: TriggerInterfaceType.ValueType  # 4
Global___TriggerInterfaceType: _TypeAlias = TriggerInterfaceType  # noqa: Y015

class _BandDataType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _BandDataTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_BandDataType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    BAND_DATA_TYPE_UNSPECIFIED: _BandDataType.ValueType  # 0
    BAND_DATA_TYPE_PSD: _BandDataType.ValueType  # 1
    BAND_DATA_TYPE_NORMALISED_PSD: _BandDataType.ValueType  # 2
    BAND_DATA_TYPE_COUNT: _BandDataType.ValueType  # 3
    BAND_DATA_TYPE_PERCENTAGE: _BandDataType.ValueType  # 4
    BAND_DATA_TYPE_BOOL: _BandDataType.ValueType  # 5
    BAND_DATA_TYPE_SPECTRUM: _BandDataType.ValueType  # 6
    BAND_DATA_TYPE_NORMALISED_SPECTRUM: _BandDataType.ValueType  # 7
    BAND_DATA_TYPE_FREQUENCY: _BandDataType.ValueType  # 8
    BAND_DATA_TYPE_AMPLITUDE: _BandDataType.ValueType  # 9
    BAND_DATA_TYPE_TEMPERATURE_BAND: _BandDataType.ValueType  # 10
    BAND_DATA_TYPE_OTHER: _BandDataType.ValueType  # 11
    BAND_DATA_TYPE_PSD_DIFF: _BandDataType.ValueType  # 12
    BAND_DATA_TYPE_RADIANS: _BandDataType.ValueType  # 13
    BAND_DATA_TYPE_NORMALISED_01: _BandDataType.ValueType  # 14

class BandDataType(_BandDataType, metaclass=_BandDataTypeEnumTypeWrapper): ...

BAND_DATA_TYPE_UNSPECIFIED: BandDataType.ValueType  # 0
BAND_DATA_TYPE_PSD: BandDataType.ValueType  # 1
BAND_DATA_TYPE_NORMALISED_PSD: BandDataType.ValueType  # 2
BAND_DATA_TYPE_COUNT: BandDataType.ValueType  # 3
BAND_DATA_TYPE_PERCENTAGE: BandDataType.ValueType  # 4
BAND_DATA_TYPE_BOOL: BandDataType.ValueType  # 5
BAND_DATA_TYPE_SPECTRUM: BandDataType.ValueType  # 6
BAND_DATA_TYPE_NORMALISED_SPECTRUM: BandDataType.ValueType  # 7
BAND_DATA_TYPE_FREQUENCY: BandDataType.ValueType  # 8
BAND_DATA_TYPE_AMPLITUDE: BandDataType.ValueType  # 9
BAND_DATA_TYPE_TEMPERATURE_BAND: BandDataType.ValueType  # 10
BAND_DATA_TYPE_OTHER: BandDataType.ValueType  # 11
BAND_DATA_TYPE_PSD_DIFF: BandDataType.ValueType  # 12
BAND_DATA_TYPE_RADIANS: BandDataType.ValueType  # 13
BAND_DATA_TYPE_NORMALISED_01: BandDataType.ValueType  # 14
Global___BandDataType: _TypeAlias = BandDataType  # noqa: Y015

class _DetectionSeverity:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DetectionSeverityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DetectionSeverity.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DETECTION_SEVERITY_UNSPECIFIED: _DetectionSeverity.ValueType  # 0
    DETECTION_SEVERITY_LOW: _DetectionSeverity.ValueType  # 1
    DETECTION_SEVERITY_MEDIUM: _DetectionSeverity.ValueType  # 2
    DETECTION_SEVERITY_HIGH: _DetectionSeverity.ValueType  # 3

class DetectionSeverity(_DetectionSeverity, metaclass=_DetectionSeverityEnumTypeWrapper):
    """DetectionSeverity is used to define the severity of a detection"""

DETECTION_SEVERITY_UNSPECIFIED: DetectionSeverity.ValueType  # 0
DETECTION_SEVERITY_LOW: DetectionSeverity.ValueType  # 1
DETECTION_SEVERITY_MEDIUM: DetectionSeverity.ValueType  # 2
DETECTION_SEVERITY_HIGH: DetectionSeverity.ValueType  # 3
Global___DetectionSeverity: _TypeAlias = DetectionSeverity  # noqa: Y015

@_typing.final
class Backup(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    SERIAL_NUMBER_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    S3_KEY_FIELD_NUMBER: _builtins.int
    COMMENT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """file name e.g. autobackup-2024-01-01-15-04-23json"""
    content: _builtins.bytes
    """contains a gzipped json backup that gets base64 encoded
    this should be empty on the portal
    """
    serial_number: _builtins.str
    title: _builtins.str
    """file title e.g. autobackup"""
    type: _builtins.str
    """declares the type of backup e.g. auto, manual or portal"""
    s3_key: _builtins.str
    """s3 key (path for file) for creating a pre signed url.
    this is used for uploading and downloading portal backups
    """
    comment: _builtins.str
    """should only populate when serving the ui"""
    @_builtins.property
    def time(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        content: _builtins.bytes = ...,
        serial_number: _builtins.str = ...,
        title: _builtins.str = ...,
        time: _timestamp_pb2.Timestamp | None = ...,
        type: _builtins.str = ...,
        s3_key: _builtins.str = ...,
        comment: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time", b"time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["comment", b"comment", "content", b"content", "name", b"name", "s3_key", b"s3_key", "serial_number", b"serial_number", "time", b"time", "title", b"title", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Backup: _TypeAlias = Backup  # noqa: Y015

@_typing.final
class GetSystemBackupsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetSystemBackupsRequest: _TypeAlias = GetSystemBackupsRequest  # noqa: Y015

@_typing.final
class GetSystemBackupsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BACKUPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def backups(self) -> _containers.RepeatedCompositeFieldContainer[Global___Backup]: ...
    def __init__(
        self,
        *,
        backups: _abc.Iterable[Global___Backup] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["backups", b"backups"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetSystemBackupsResponse: _TypeAlias = GetSystemBackupsResponse  # noqa: Y015

@_typing.final
class CommonHeader(_message.Message):
    """CommonHeader the header fields common to all data packet types"""

    DESCRIPTOR: _descriptor.Descriptor

    TIME_FIELD_NUMBER: _builtins.int
    NUM_CHANNELS_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_FIELD_NUMBER: _builtins.int
    CHANNEL_SPACING_FIELD_NUMBER: _builtins.int
    GAUGE_LENGTH_FIELD_NUMBER: _builtins.int
    START_CHANNEL_FIELD_NUMBER: _builtins.int
    END_OF_REPLAY_FIELD_NUMBER: _builtins.int
    FIBER_FLIPPED_FIELD_NUMBER: _builtins.int
    LOOP_REMOVED_FIELD_NUMBER: _builtins.int
    HAS_DROPPED_SAMPLES_FIELD_NUMBER: _builtins.int
    TIMESERIES_DATA_TYPE_FIELD_NUMBER: _builtins.int
    DEMOD_DATA_TYPE_FIELD_NUMBER: _builtins.int
    num_channels: _builtins.int
    """num_channels is the number of distance channels in the packet"""
    sample_rate: _builtins.float
    """sample_rate defines the sample rate for the samples in this packet"""
    channel_spacing: _builtins.float
    """channel_spacing is the width of each channel in meters"""
    gauge_length: _builtins.float
    """gauge_length is the length of the acquition gauge in meters"""
    start_channel: _builtins.int
    """start_channel is the channel number of the first channel in the packet
    if loop removed = true, then this is the loop-removed channel number,
    not the raw channel number.
    """
    end_of_replay: _builtins.bool
    """end_of_replay is whether this packet is the last in a replay"""
    fiber_flipped: _builtins.bool
    """fiber_flipped is whether the channels in this packet have been flipped
    since acquisition
    """
    loop_removed: _builtins.bool
    """loop_removed is whether loops have been removed this packet"""
    has_dropped_samples: _builtins.bool
    """has_dropped_samples is true if samples were dropped within this packet"""
    timeseries_data_type: Global___TimeseriesDataType.ValueType
    """timeseries_data_type is the type of timeseries data in this packet"""
    demod_data_type: Global___DemodDataType.ValueType
    """demod_data_type is the type of demod data in this packet"""
    @_builtins.property
    def time(self) -> _timestamp_pb2.Timestamp:
        """time is the time associated with this packet"""

    def __init__(
        self,
        *,
        time: _timestamp_pb2.Timestamp | None = ...,
        num_channels: _builtins.int = ...,
        sample_rate: _builtins.float = ...,
        channel_spacing: _builtins.float = ...,
        gauge_length: _builtins.float = ...,
        start_channel: _builtins.int = ...,
        end_of_replay: _builtins.bool = ...,
        fiber_flipped: _builtins.bool = ...,
        loop_removed: _builtins.bool = ...,
        has_dropped_samples: _builtins.bool = ...,
        timeseries_data_type: Global___TimeseriesDataType.ValueType = ...,
        demod_data_type: Global___DemodDataType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time", b"time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_spacing", b"channel_spacing", "demod_data_type", b"demod_data_type", "end_of_replay", b"end_of_replay", "fiber_flipped", b"fiber_flipped", "gauge_length", b"gauge_length", "has_dropped_samples", b"has_dropped_samples", "loop_removed", b"loop_removed", "num_channels", b"num_channels", "sample_rate", b"sample_rate", "start_channel", b"start_channel", "time", b"time", "timeseries_data_type", b"timeseries_data_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CommonHeader: _TypeAlias = CommonHeader  # noqa: Y015

@_typing.final
class FFTHeader(_message.Message):
    """FFTHeader the header details for an FFT packet"""

    DESCRIPTOR: _descriptor.Descriptor

    COMMON_HEADER_FIELD_NUMBER: _builtins.int
    NUM_BINS_FIELD_NUMBER: _builtins.int
    BIN_RES_FIELD_NUMBER: _builtins.int
    AVERAGING_TYPE_FIELD_NUMBER: _builtins.int
    CHANNEL_STEP_FIELD_NUMBER: _builtins.int
    NORMALISED_FIELD_NUMBER: _builtins.int
    HAS_POWER_DATA_FIELD_NUMBER: _builtins.int
    HAS_COMPLEX_DATA_FIELD_NUMBER: _builtins.int
    num_bins: _builtins.int
    """num_bins is the number of bins in the FFT. Sample slice is of size
    number channels * number bins (*2 if output is complex type)
    """
    bin_res: _builtins.float
    """bin_res is the resolution of each bin in Hz"""
    averaging_type: Global___AveragingType.ValueType
    """averaging_type is the type of averaging applied to the FFT output"""
    channel_step: _builtins.int
    """channel_step is the step between channels? meters?"""
    normalised: _builtins.bool
    """normalised is whether the FFT output was normalised"""
    has_power_data: _builtins.bool
    """has_power_data is whether the FFT output been converted to power"""
    has_complex_data: _builtins.bool
    """has_complex_data is whether the FFT output is complex"""
    @_builtins.property
    def common_header(self) -> Global___CommonHeader:
        """common_header are the header fields common to all data packet types"""

    def __init__(
        self,
        *,
        common_header: Global___CommonHeader | None = ...,
        num_bins: _builtins.int = ...,
        bin_res: _builtins.float = ...,
        averaging_type: Global___AveragingType.ValueType = ...,
        channel_step: _builtins.int = ...,
        normalised: _builtins.bool = ...,
        has_power_data: _builtins.bool = ...,
        has_complex_data: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["common_header", b"common_header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["averaging_type", b"averaging_type", "bin_res", b"bin_res", "channel_step", b"channel_step", "common_header", b"common_header", "has_complex_data", b"has_complex_data", "has_power_data", b"has_power_data", "normalised", b"normalised", "num_bins", b"num_bins"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FFTHeader: _TypeAlias = FFTHeader  # noqa: Y015

@_typing.final
class FFTPacket(_message.Message):
    """FFT a message type for representing the output from a Fast Fourier Transform"""

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    SAMPLES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def header(self) -> Global___FFTHeader:
        """header specifies the various fields of the FFT output"""

    @_builtins.property
    def samples(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """samples are the fft values
        Real output is the order C1B1, C1B2..., C2B1, C2B2...
        Complex output is the order C1B1R, C1B1I, C1B2R, C1B2I...
        """

    def __init__(
        self,
        *,
        header: Global___FFTHeader | None = ...,
        samples: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "samples", b"samples"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FFTPacket: _TypeAlias = FFTPacket  # noqa: Y015

@_typing.final
class GPS(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PPS_TIME_FIELD_NUMBER: _builtins.int
    PPS_SAMPLE_OFFSET_FIELD_NUMBER: _builtins.int
    ACCURACY_FIELD_NUMBER: _builtins.int
    OVERFLOW_FIELD_NUMBER: _builtins.int
    VALIDITY_FIELD_NUMBER: _builtins.int
    SYNCED_FIELD_NUMBER: _builtins.int
    GPS_TIME_FIELD_NUMBER: _builtins.int
    pps_time: _builtins.int
    """GPS time (week and seconds only) of latest sample aligned to GPS 1PPS"""
    pps_sample_offset: _builtins.int
    """Sample counter value of sample at ppsTime"""
    accuracy: _builtins.int
    """GPS accuracy, ns, up to 2^24"""
    overflow: _builtins.bool
    """GPS accuracy is greater than 2^24"""
    validity: _builtins.bool
    """GPS time is valid"""
    synced: _builtins.bool
    """clocks synced"""
    gps_time: _builtins.bool
    """true for GPS time, false for PC time"""
    def __init__(
        self,
        *,
        pps_time: _builtins.int = ...,
        pps_sample_offset: _builtins.int = ...,
        accuracy: _builtins.int = ...,
        overflow: _builtins.bool = ...,
        validity: _builtins.bool = ...,
        synced: _builtins.bool = ...,
        gps_time: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accuracy", b"accuracy", "gps_time", b"gps_time", "overflow", b"overflow", "pps_sample_offset", b"pps_sample_offset", "pps_time", b"pps_time", "synced", b"synced", "validity", b"validity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GPS: _TypeAlias = GPS  # noqa: Y015

@_typing.final
class Triggers(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TRIGGER_FLAGS_FIELD_NUMBER: _builtins.int
    AXLE_COUNTER_STATES_FIELD_NUMBER: _builtins.int
    TRIGGER_TYPE_FIELD_NUMBER: _builtins.int
    TRIGGER_SAMPLE_OFFSETS_FIELD_NUMBER: _builtins.int
    trigger_type: Global___TriggerInterfaceType.ValueType
    @_builtins.property
    def trigger_flags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bool]:
        """8 bit flags for triggers 0-7 representing occurrence of trigger / 
        state-change
        """

    @_builtins.property
    def axle_counter_states(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bool]:
        """8 bit hi/lo states for axle counters 0-7, only used when 
        TriggerType = TRIGGER_INTERFACE_TYPE_AXLE_COUNTER
        """

    @_builtins.property
    def trigger_sample_offsets(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """sample offset per trigger from first sample in packet"""

    def __init__(
        self,
        *,
        trigger_flags: _abc.Iterable[_builtins.bool] | None = ...,
        axle_counter_states: _abc.Iterable[_builtins.bool] | None = ...,
        trigger_type: Global___TriggerInterfaceType.ValueType = ...,
        trigger_sample_offsets: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["axle_counter_states", b"axle_counter_states", "trigger_flags", b"trigger_flags", "trigger_sample_offsets", b"trigger_sample_offsets", "trigger_type", b"trigger_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Triggers: _TypeAlias = Triggers  # noqa: Y015

@_typing.final
class TimeseriesHeader(_message.Message):
    """TimeseriesHeader defines the header fields common to all timeseries packets."""

    DESCRIPTOR: _descriptor.Descriptor

    COMMON_HEADER_FIELD_NUMBER: _builtins.int
    SAMPLE_COUNT_FIELD_NUMBER: _builtins.int
    NUM_SAMPLES_FIELD_NUMBER: _builtins.int
    CHANNEL_STEP_FIELD_NUMBER: _builtins.int
    GPS_FIELD_NUMBER: _builtins.int
    TRIGGERS_FIELD_NUMBER: _builtins.int
    sample_count: _builtins.int
    """Sequential sample counter for the first sample in the packet"""
    num_samples: _builtins.int
    """Number of samples per channel in this packet"""
    channel_step: _builtins.int
    """Normally 1 for contiguous channels. The last channel is 
    StartChannel + NumChannels*ChannelStep on the fibre
    """
    @_builtins.property
    def common_header(self) -> Global___CommonHeader:
        """common_header are the header fields common to all data packet types"""

    @_builtins.property
    def gps(self) -> Global___GPS: ...
    @_builtins.property
    def triggers(self) -> Global___Triggers: ...
    def __init__(
        self,
        *,
        common_header: Global___CommonHeader | None = ...,
        sample_count: _builtins.int = ...,
        num_samples: _builtins.int = ...,
        channel_step: _builtins.int = ...,
        gps: Global___GPS | None = ...,
        triggers: Global___Triggers | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["common_header", b"common_header", "gps", b"gps", "triggers", b"triggers"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_step", b"channel_step", "common_header", b"common_header", "gps", b"gps", "num_samples", b"num_samples", "sample_count", b"sample_count", "triggers", b"triggers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TimeseriesHeader: _TypeAlias = TimeseriesHeader  # noqa: Y015

@_typing.final
class TimeseriesPacket(_message.Message):
    """TimeseriesPacket defines the protobuf version of the
    standard timeseries packets. A normal packet would include
    the header and samples. Optionally the raw_frames could be included
    which include the raw FPGA frames (header + samples) unprocessed. In this
    configuration the (decoded) float samples would normally not be included.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    SAMPLES_FIELD_NUMBER: _builtins.int
    RAW_FRAMES_FIELD_NUMBER: _builtins.int
    INT_SAMPLES_FIELD_NUMBER: _builtins.int
    F64_SAMPLES_FIELD_NUMBER: _builtins.int
    raw_frames: _builtins.bytes
    """raw_frames are the raw FPGA frames (header + samples) unprocessed.
    optionally the raw frames
    """
    @_builtins.property
    def header(self) -> Global___TimeseriesHeader: ...
    @_builtins.property
    def samples(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """samples in the order of S1C1, S1C2,S1,CN... SMC1, SMC2..."""

    @_builtins.property
    def int_samples(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """samples as integer (usually differential) as S1C1, S1C2..."""

    @_builtins.property
    def f64_samples(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """samples as float64 (usually differential) as S1C1, S1C2..."""

    def __init__(
        self,
        *,
        header: Global___TimeseriesHeader | None = ...,
        samples: _abc.Iterable[_builtins.float] | None = ...,
        raw_frames: _builtins.bytes = ...,
        int_samples: _abc.Iterable[_builtins.int] | None = ...,
        f64_samples: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["f64_samples", b"f64_samples", "header", b"header", "int_samples", b"int_samples", "raw_frames", b"raw_frames", "samples", b"samples"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TimeseriesPacket: _TypeAlias = TimeseriesPacket  # noqa: Y015

@_typing.final
class BandDataInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BAND_DATA_TYPE_FIELD_NUMBER: _builtins.int
    START_FIELD_NUMBER: _builtins.int
    END_FIELD_NUMBER: _builtins.int
    AVERAGING_TYPE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    band_data_type: Global___BandDataType.ValueType
    start: _builtins.float
    """Start frequency of the band, Hz"""
    end: _builtins.float
    """End frequency of the band, Hz"""
    averaging_type: Global___AveragingType.ValueType
    description: _builtins.str
    source: _builtins.str
    def __init__(
        self,
        *,
        band_data_type: Global___BandDataType.ValueType = ...,
        start: _builtins.float = ...,
        end: _builtins.float = ...,
        averaging_type: Global___AveragingType.ValueType = ...,
        description: _builtins.str = ...,
        source: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["averaging_type", b"averaging_type", "band_data_type", b"band_data_type", "description", b"description", "end", b"end", "source", b"source", "start", b"start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BandDataInfo: _TypeAlias = BandDataInfo  # noqa: Y015

@_typing.final
class BandHeader(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMON_HEADER_FIELD_NUMBER: _builtins.int
    BAND_DATA_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def common_header(self) -> Global___CommonHeader: ...
    @_builtins.property
    def band_data_info(self) -> _containers.RepeatedCompositeFieldContainer[Global___BandDataInfo]: ...
    def __init__(
        self,
        *,
        common_header: Global___CommonHeader | None = ...,
        band_data_info: _abc.Iterable[Global___BandDataInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["common_header", b"common_header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["band_data_info", b"band_data_info", "common_header", b"common_header"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BandHeader: _TypeAlias = BandHeader  # noqa: Y015

@_typing.final
class BandPacket(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    SAMPLES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def header(self) -> Global___BandHeader: ...
    @_builtins.property
    def samples(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        header: Global___BandHeader | None = ...,
        samples: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "samples", b"samples"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BandPacket: _TypeAlias = BandPacket  # noqa: Y015

@_typing.final
class LatLng(_message.Message):
    """LatLng is a simple message to hold a latitude and longitude
    TBD use the google lat long type
    """

    DESCRIPTOR: _descriptor.Descriptor

    LATITUDE_FIELD_NUMBER: _builtins.int
    LONGITUDE_FIELD_NUMBER: _builtins.int
    latitude: _builtins.float
    longitude: _builtins.float
    def __init__(
        self,
        *,
        latitude: _builtins.float = ...,
        longitude: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["latitude", b"latitude", "longitude", b"longitude"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LatLng: _TypeAlias = LatLng  # noqa: Y015

@_typing.final
class CustomScale(_message.Message):
    """CustomScale defines a custom scale value for a position
    along the fiber. For example 100.0 kp
    """

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    READABLE_SCALE_FIELD_NUMBER: _builtins.int
    value: _builtins.float
    """numberical value of the scale e.g. 7.123"""
    readable_scale: _builtins.str
    """readable_scale includes the custom scale name and value, e.g. "kp7.123" """
    def __init__(
        self,
        *,
        value: _builtins.float = ...,
        readable_scale: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["readable_scale", b"readable_scale", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CustomScale: _TypeAlias = CustomScale  # noqa: Y015

@_typing.final
class Position(_message.Message):
    """Position provides a position along the fiber,
    including the custom scale or OD.
    """

    DESCRIPTOR: _descriptor.Descriptor

    POSITION_FIELD_NUMBER: _builtins.int
    CUSTOM_SCALE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def position(self) -> Global___LatLng:
        """LatLng holds the latitude and longitude of the position."""

    @_builtins.property
    def custom_scale(self) -> Global___CustomScale:
        """CustomScale holds the custom scale associated with the position,
        or the optical distance if the customer scale hasn't been configured.
        """

    def __init__(
        self,
        *,
        position: Global___LatLng | None = ...,
        custom_scale: Global___CustomScale | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["custom_scale", b"custom_scale", "position", b"position"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["custom_scale", b"custom_scale", "position", b"position"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Position: _TypeAlias = Position  # noqa: Y015

@_typing.final
class DistanceToZone(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DIRECTION_FIELD_NUMBER: _builtins.int
    SEPARATION_FIELD_NUMBER: _builtins.int
    NOTES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """name of the zone"""
    direction: _builtins.str
    """direction to the zone"""
    separation: _builtins.float
    """separation to the zone in meters"""
    notes: _builtins.str
    """notes about the distance to the zone"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        direction: _builtins.str = ...,
        separation: _builtins.float = ...,
        notes: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["direction", b"direction", "name", b"name", "notes", b"notes", "separation", b"separation"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DistanceToZone: _TypeAlias = DistanceToZone  # noqa: Y015

@_typing.final
class Detection(_message.Message):
    """Detection is used to define a detection event"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    START_TIME_FIELD_NUMBER: _builtins.int
    LAST_UPDATE_TIME_FIELD_NUMBER: _builtins.int
    LATEST_POSITION_FIELD_NUMBER: _builtins.int
    LATEST_OD_M_FIELD_NUMBER: _builtins.int
    CLASSIFICATION_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    SPEED_FIELD_NUMBER: _builtins.int
    LATEST_FULL_POSITION_FIELD_NUMBER: _builtins.int
    NODE_FIELD_NUMBER: _builtins.int
    NODE_ID_FIELD_NUMBER: _builtins.int
    POIS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """id is a unique ID for the detection"""
    latest_od_m: _builtins.float
    """latest_od_m is the optical distance in metres corresponding to
    the latest position, I think we might want to deprecate this or include
    information about flip and loop remove.
    """
    classification: _builtins.str
    """classification is the classification of the detection
    For example "Digging"
    """
    severity: Global___DetectionSeverity.ValueType
    """severity, low, medium or high"""
    speed: _builtins.float
    """speed is the speed of the detection in mps"""
    node: _builtins.str
    """source node name from event"""
    node_id: _builtins.str
    """source node id from event"""
    @_builtins.property
    def start_time(self) -> _timestamp_pb2.Timestamp:
        """start_time is the time the detection was first detected"""

    @_builtins.property
    def last_update_time(self) -> _timestamp_pb2.Timestamp:
        """last_update_time is the time the detection was last updated"""

    @_builtins.property
    def latest_position(self) -> Global___LatLng:
        """latest_position is the latest position of the detection"""

    @_builtins.property
    def latest_full_position(self) -> Global___Position:
        """latest_full_position is the full position of the detection
        including the custom scale. It is preferred over
        latest_position.
        """

    @_builtins.property
    def pois(self) -> Global___DistanceToZone:
        """pois are the points of interest for the detection"""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        start_time: _timestamp_pb2.Timestamp | None = ...,
        last_update_time: _timestamp_pb2.Timestamp | None = ...,
        latest_position: Global___LatLng | None = ...,
        latest_od_m: _builtins.float = ...,
        classification: _builtins.str = ...,
        severity: Global___DetectionSeverity.ValueType = ...,
        speed: _builtins.float = ...,
        latest_full_position: Global___Position | None = ...,
        node: _builtins.str = ...,
        node_id: _builtins.str = ...,
        pois: Global___DistanceToZone | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["last_update_time", b"last_update_time", "latest_full_position", b"latest_full_position", "latest_position", b"latest_position", "pois", b"pois", "start_time", b"start_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["classification", b"classification", "id", b"id", "last_update_time", b"last_update_time", "latest_full_position", b"latest_full_position", "latest_od_m", b"latest_od_m", "latest_position", b"latest_position", "node", b"node", "node_id", b"node_id", "pois", b"pois", "severity", b"severity", "speed", b"speed", "start_time", b"start_time"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Detection: _TypeAlias = Detection  # noqa: Y015
