# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from onyxpublic.api import onyx_pb2 as api_dot_onyx__pb2
from onyxpublic.common import common_pb2 as common_dot_common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/onyx_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OnyxStub(object):
    """Protobuf specification for Onyx gRPC API.
    Note that in general there are two instances of the Onyx software running
    on a device. Once for Fiber 1 and one for Fiber2.
    Call the API on the correct software instance to get interact with one fiber
    or the other.
    --------------------------------------------------------------------------
    Data Extraction:
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Extract = channel.unary_unary(
                '/api.Onyx/Extract',
                request_serializer=api_dot_onyx__pb2.ExtractionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CancelExtract = channel.unary_unary(
                '/api.Onyx/CancelExtract',
                request_serializer=api_dot_onyx__pb2.CancelExtractionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ExtractStatus = channel.unary_unary(
                '/api.Onyx/ExtractStatus',
                request_serializer=api_dot_onyx__pb2.ExtractionStatusRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.ExtractionStatusResponse.FromString,
                _registered_method=True)
        self.ExtractStatuses = channel.unary_unary(
                '/api.Onyx/ExtractStatuses',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.ExtractionStatusResponse.FromString,
                _registered_method=True)
        self.SetAWSCredentials = channel.unary_unary(
                '/api.Onyx/SetAWSCredentials',
                request_serializer=api_dot_onyx__pb2.NamedAWSCredentials.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetConfigurationBackup = channel.unary_unary(
                '/api.Onyx/GetConfigurationBackup',
                request_serializer=api_dot_onyx__pb2.BackupRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.BackupResponse.FromString,
                _registered_method=True)
        self.RestoreConfiguration = channel.unary_unary(
                '/api.Onyx/RestoreConfiguration',
                request_serializer=api_dot_onyx__pb2.RestoreRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.RestoreResponse.FromString,
                _registered_method=True)
        self.GetAcquisitionStats = channel.unary_unary(
                '/api.Onyx/GetAcquisitionStats',
                request_serializer=api_dot_onyx__pb2.AcquisitionStatsRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.AcquisitionStatsResponse.FromString,
                _registered_method=True)
        self.AcknowledgeAllSysEvents = channel.unary_unary(
                '/api.Onyx/AcknowledgeAllSysEvents',
                request_serializer=api_dot_onyx__pb2.AcknowledgeAllSysEventsRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.AcknowledgeAllSysEventsResponse.FromString,
                _registered_method=True)
        self.GetSystemStatusSummary = channel.unary_unary(
                '/api.Onyx/GetSystemStatusSummary',
                request_serializer=api_dot_onyx__pb2.SystemStatusSummaryRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.SystemStatusSummaryResponse.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/api.Onyx/GetSystemStatus',
                request_serializer=api_dot_onyx__pb2.SystemStatusRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.SystemStatusResponse.FromString,
                _registered_method=True)
        self.GetSystemEvents = channel.unary_unary(
                '/api.Onyx/GetSystemEvents',
                request_serializer=api_dot_onyx__pb2.SystemEventsRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.SystemEventsResponse.FromString,
                _registered_method=True)
        self.GetReportableSystemEvents = channel.unary_unary(
                '/api.Onyx/GetReportableSystemEvents',
                request_serializer=api_dot_onyx__pb2.ReportableSystemEventsRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.ReportableSystemEventsResponse.FromString,
                _registered_method=True)
        self.GetOnyxSoftwareStatus = channel.unary_unary(
                '/api.Onyx/GetOnyxSoftwareStatus',
                request_serializer=api_dot_onyx__pb2.OnyxSoftwareStatusRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.OnyxSoftwareStatusResponse.FromString,
                _registered_method=True)
        self.GetDetections = channel.unary_unary(
                '/api.Onyx/GetDetections',
                request_serializer=api_dot_onyx__pb2.DetectionsRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.DetectionsResponse.FromString,
                _registered_method=True)
        self.GetIdentification = channel.unary_unary(
                '/api.Onyx/GetIdentification',
                request_serializer=api_dot_onyx__pb2.IdentificationRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.IdentificationResponse.FromString,
                _registered_method=True)
        self.StartManualRecord = channel.unary_unary(
                '/api.Onyx/StartManualRecord',
                request_serializer=api_dot_onyx__pb2.StartManualRecordRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.StartManualRecordResponse.FromString,
                _registered_method=True)
        self.StopManualRecord = channel.unary_unary(
                '/api.Onyx/StopManualRecord',
                request_serializer=api_dot_onyx__pb2.StopManualRecordingRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.StopManualRecordingResponse.FromString,
                _registered_method=True)
        self.ManualRecordStatus = channel.unary_unary(
                '/api.Onyx/ManualRecordStatus',
                request_serializer=api_dot_onyx__pb2.ManualRecordStatusRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.ManualRecordStatusResponse.FromString,
                _registered_method=True)
        self.StartRecorders = channel.unary_unary(
                '/api.Onyx/StartRecorders',
                request_serializer=api_dot_onyx__pb2.StartRecordersRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.StartRecordersResponse.FromString,
                _registered_method=True)
        self.StopRecorders = channel.unary_unary(
                '/api.Onyx/StopRecorders',
                request_serializer=api_dot_onyx__pb2.StopRecordersRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.StopRecordersResponse.FromString,
                _registered_method=True)
        self.GetRecordersStatus = channel.unary_unary(
                '/api.Onyx/GetRecordersStatus',
                request_serializer=api_dot_onyx__pb2.GetRecordersStatusRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.GetRecordersStatusResponse.FromString,
                _registered_method=True)
        self.GetModuleConfig = channel.unary_unary(
                '/api.Onyx/GetModuleConfig',
                request_serializer=api_dot_onyx__pb2.GetModuleConfigRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.GetModuleConfigResponse.FromString,
                _registered_method=True)
        self.SetModuleConfig = channel.unary_unary(
                '/api.Onyx/SetModuleConfig',
                request_serializer=api_dot_onyx__pb2.SetModuleConfigRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.SetModuleConfigResponse.FromString,
                _registered_method=True)
        self.ControlPlaylist = channel.unary_unary(
                '/api.Onyx/ControlPlaylist',
                request_serializer=api_dot_onyx__pb2.ControlPlaylistRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.ControlPlaylistResponse.FromString,
                _registered_method=True)
        self.GetPlaylistStatus = channel.unary_unary(
                '/api.Onyx/GetPlaylistStatus',
                request_serializer=api_dot_onyx__pb2.GetPlaylistStatusRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.GetPlaylistStatusResponse.FromString,
                _registered_method=True)
        self.GetSystemBackups = channel.unary_unary(
                '/api.Onyx/GetSystemBackups',
                request_serializer=common_dot_common__pb2.GetSystemBackupsRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.GetSystemBackupsResponse.FromString,
                _registered_method=True)
        self.DeleteBackup = channel.unary_unary(
                '/api.Onyx/DeleteBackup',
                request_serializer=api_dot_onyx__pb2.DeleteBackupRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.DeleteBackupResponse.FromString,
                _registered_method=True)
        self.DownloadBackup = channel.unary_unary(
                '/api.Onyx/DownloadBackup',
                request_serializer=api_dot_onyx__pb2.DownloadBackupRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.DownloadBackupResponse.FromString,
                _registered_method=True)
        self.ManualBackup = channel.unary_unary(
                '/api.Onyx/ManualBackup',
                request_serializer=api_dot_onyx__pb2.ManualBackupRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.ManualBackupResponse.FromString,
                _registered_method=True)
        self.GetManualBackupStatus = channel.unary_unary(
                '/api.Onyx/GetManualBackupStatus',
                request_serializer=api_dot_onyx__pb2.GetManualBackupStatusRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.GetManualBackupStatusResponse.FromString,
                _registered_method=True)
        self.TriggerDataBaseStatsCleanup = channel.unary_unary(
                '/api.Onyx/TriggerDataBaseStatsCleanup',
                request_serializer=api_dot_onyx__pb2.TriggerDataBaseStatsCleanupRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.TriggerDataBaseStatsCleanupResponse.FromString,
                _registered_method=True)
        self.StreamDetections = channel.unary_stream(
                '/api.Onyx/StreamDetections',
                request_serializer=api_dot_onyx__pb2.StreamDetectionsRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.StreamDetectionsResponse.FromString,
                _registered_method=True)
        self.GetTimeseriesSources = channel.unary_unary(
                '/api.Onyx/GetTimeseriesSources',
                request_serializer=api_dot_onyx__pb2.GetTimeseriesSourcesRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.GetTimeseriesSourcesResponse.FromString,
                _registered_method=True)
        self.GetTimeseries = channel.unary_stream(
                '/api.Onyx/GetTimeseries',
                request_serializer=api_dot_onyx__pb2.GetTimeseriesRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.TimeseriesPacket.FromString,
                _registered_method=True)
        self.StreamTimeseries = channel.unary_stream(
                '/api.Onyx/StreamTimeseries',
                request_serializer=api_dot_onyx__pb2.StreamTimeseriesRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.TimeseriesPacket.FromString,
                _registered_method=True)
        self.StreamTimeseriesOut = channel.unary_stream(
                '/api.Onyx/StreamTimeseriesOut',
                request_serializer=api_dot_onyx__pb2.StreamTimeseriesOutRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.StreamTimeseriesOutResponse.FromString,
                _registered_method=True)
        self.StreamTimeseriesIn = channel.stream_unary(
                '/api.Onyx/StreamTimeseriesIn',
                request_serializer=api_dot_onyx__pb2.StreamTimeseriesInRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.StreamTimeseriesInResponse.FromString,
                _registered_method=True)
        self.GetFiberLength = channel.unary_unary(
                '/api.Onyx/GetFiberLength',
                request_serializer=api_dot_onyx__pb2.FiberLengthRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.FiberLengthResponse.FromString,
                _registered_method=True)
        self.GetChainStatus = channel.unary_unary(
                '/api.Onyx/GetChainStatus',
                request_serializer=api_dot_onyx__pb2.ChainStatusRequest.SerializeToString,
                response_deserializer=api_dot_onyx__pb2.ChainStatusResponse.FromString,
                _registered_method=True)


class OnyxServicer(object):
    """Protobuf specification for Onyx gRPC API.
    Note that in general there are two instances of the Onyx software running
    on a device. Once for Fiber 1 and one for Fiber2.
    Call the API on the correct software instance to get interact with one fiber
    or the other.
    --------------------------------------------------------------------------
    Data Extraction:
    """

    def Extract(self, request, context):
        """Submit a data extraction request. This can fail if the server's queue for
        data extractions is full. This return as soon as the request has been
        submitted; it does not wait for the extraction process to complete.
        To check on progress and success/failure, use the ExtractStatus RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelExtract(self, request, context):
        """Request cancellation of a data extraction, and succeeds even if no such
        data extraction job currently exists.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractStatus(self, request, context):
        """Request the status of a current or recent extraction requests by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractStatuses(self, request, context):
        """Request the status of all current and recent extraction requests.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAWSCredentials(self, request, context):
        """Set the AWS Credentials to be used for subsequent AWS access, e.g. data
        extractions to S3 buckets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfigurationBackup(self, request, context):
        """GetConfigurationBackup() returns the configuration backup as a JSON string
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreConfiguration(self, request, context):
        """RestoreConfiguration() retores the configuration for a system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAcquisitionStats(self, request, context):
        """GetAcquisitionStats returns the current acquisition settings of the system
        This acquisition details can de different for each fiber. Call this service
        on the fiber you are interested in, e.g. onyx software instance 1 or 2
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeAllSysEvents(self, request, context):
        """AcknowledgeAllSysEvents acknowledges all the system events
        present on the node on which it was called. The user requires the
        ManageEvents permission to make a valid call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatusSummary(self, request, context):
        """GetSystemStatusSummary returns a top level summary of the system status
        This includes an overall status for disks, temperatures, database etc.
        Use the GetSystemStatus to drill into these areas for further information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """GetSystemStatus returns the status of the system.
        Status includes temperatures, cpu load, disk usage, etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemEvents(self, request, context):
        """GetSystemEvents returns a list of system events. System Events are
        errors or information messages about the state of the system.
        If the system is behaving normally there should be no error level
        events reported.
        Examples of Error Events:
        - Data not flowing
        - Disk Full
        - Over Temperature
        Example of Information Events:
        - System Configuration Changed
        - Event output temporarily disabled
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReportableSystemEvents(self, request, context):
        """GetReportableSystemEvents returns a list of reportable system events.
        Reportable events are important events that have been in a bad status for
        a period of time. Important events include, FiberBreak, DataNotFlowing,
        DiskFull, etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOnyxSoftwareStatus(self, request, context):
        """GetOnyxSoftwareStatus returns the status of the Onyx software.
        Normally an Onyx system runs two instances of the software,
        one for each fiber. Status includes software uptime, sensor data uptime,
        software version etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDetections(self, request, context):
        """GetDetections returns a list of detections that have been made
        by the system. Each detection includes it's time, classification
        and position.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIdentification(self, request, context):
        """-------------------------------------------------------------------------
        GetIdentification returns information that can be used to identify a system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartManualRecord(self, request, context):
        """StartManualRecord starts the manual recorder for timeseries data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopManualRecord(self, request, context):
        """StopManualRecord stops the manual recorder
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManualRecordStatus(self, request, context):
        """GetRecordersStatus return the status of the manual recorder
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRecorders(self, request, context):
        """StartRecorders starts all the recorders recording to the given path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRecorders(self, request, context):
        """StopRecorders stops all the recorders recording
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecordersStatus(self, request, context):
        """GetRecordersStatus return the status of the recorders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModuleConfig(self, request, context):
        """GetModuleConfig returns the configuration of an available 
        module in the module registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetModuleConfig(self, request, context):
        """SetModuleConfig sets the configuration of a module
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlPlaylist(self, request, context):
        """ControlPlaylist is used to control playlist replay
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistStatus(self, request, context):
        """GetPlaylistStatus returns the status of the playlist replay.
        The replay can include the list of recordings in the selected playlist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemBackups(self, request, context):
        """GetSystemBackups returns the systems local and portal backups
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBackup(self, request, context):
        """DeleteBackup deletes the chosen backup from the system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadBackup(self, request, context):
        """DownloadBackup returns content of a system backup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManualBackup(self, request, context):
        """ManualBackup prompts the system to manually backup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManualBackupStatus(self, request, context):
        """GetManualBackupStatus gets status of manual backup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerDataBaseStatsCleanup(self, request, context):
        """TriggerDataBaseStatsCleanup triggers the cleanup of the database stats
        This normally runs on a schedule but calling this will trigger it to run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDetections(self, request, context):
        """StreamDetections requests a stream of events from the server
        This publishes detected events to the stream as they arrive in
        the event store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeseriesSources(self, request, context):
        """GetTimeseriesSources returns the list of timeseries sources that are
        available for streaming with the GetTimeSeries service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeseries(self, request, context):
        """GetTimeseries streams timeseries data from the given source.
        Deprecated: Use StreamTimeseriesOut instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTimeseries(self, request, context):
        """StreamTimeseries streams timeseries data from the given source.
        Deprecated: Use StreamTimeseriesOut instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTimeseriesOut(self, request, context):
        """Stream timeseries packets out from the given source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTimeseriesIn(self, request_iterator, context):
        """StreamTimeseriesIn streams timeseries data into the given sink.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFiberLength(self, request, context):
        """GetFiberLength returns the length of the fiber for a given FiberNumber
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChainStatus(self, request, context):
        """GetChainStatus returns the name of the current chain and if it is unsaved
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OnyxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Extract': grpc.unary_unary_rpc_method_handler(
                    servicer.Extract,
                    request_deserializer=api_dot_onyx__pb2.ExtractionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CancelExtract': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelExtract,
                    request_deserializer=api_dot_onyx__pb2.CancelExtractionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ExtractStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractStatus,
                    request_deserializer=api_dot_onyx__pb2.ExtractionStatusRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.ExtractionStatusResponse.SerializeToString,
            ),
            'ExtractStatuses': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractStatuses,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=api_dot_onyx__pb2.ExtractionStatusResponse.SerializeToString,
            ),
            'SetAWSCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAWSCredentials,
                    request_deserializer=api_dot_onyx__pb2.NamedAWSCredentials.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetConfigurationBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfigurationBackup,
                    request_deserializer=api_dot_onyx__pb2.BackupRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.BackupResponse.SerializeToString,
            ),
            'RestoreConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreConfiguration,
                    request_deserializer=api_dot_onyx__pb2.RestoreRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.RestoreResponse.SerializeToString,
            ),
            'GetAcquisitionStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAcquisitionStats,
                    request_deserializer=api_dot_onyx__pb2.AcquisitionStatsRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.AcquisitionStatsResponse.SerializeToString,
            ),
            'AcknowledgeAllSysEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeAllSysEvents,
                    request_deserializer=api_dot_onyx__pb2.AcknowledgeAllSysEventsRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.AcknowledgeAllSysEventsResponse.SerializeToString,
            ),
            'GetSystemStatusSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatusSummary,
                    request_deserializer=api_dot_onyx__pb2.SystemStatusSummaryRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.SystemStatusSummaryResponse.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=api_dot_onyx__pb2.SystemStatusRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.SystemStatusResponse.SerializeToString,
            ),
            'GetSystemEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemEvents,
                    request_deserializer=api_dot_onyx__pb2.SystemEventsRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.SystemEventsResponse.SerializeToString,
            ),
            'GetReportableSystemEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportableSystemEvents,
                    request_deserializer=api_dot_onyx__pb2.ReportableSystemEventsRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.ReportableSystemEventsResponse.SerializeToString,
            ),
            'GetOnyxSoftwareStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOnyxSoftwareStatus,
                    request_deserializer=api_dot_onyx__pb2.OnyxSoftwareStatusRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.OnyxSoftwareStatusResponse.SerializeToString,
            ),
            'GetDetections': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetections,
                    request_deserializer=api_dot_onyx__pb2.DetectionsRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.DetectionsResponse.SerializeToString,
            ),
            'GetIdentification': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentification,
                    request_deserializer=api_dot_onyx__pb2.IdentificationRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.IdentificationResponse.SerializeToString,
            ),
            'StartManualRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.StartManualRecord,
                    request_deserializer=api_dot_onyx__pb2.StartManualRecordRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.StartManualRecordResponse.SerializeToString,
            ),
            'StopManualRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.StopManualRecord,
                    request_deserializer=api_dot_onyx__pb2.StopManualRecordingRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.StopManualRecordingResponse.SerializeToString,
            ),
            'ManualRecordStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ManualRecordStatus,
                    request_deserializer=api_dot_onyx__pb2.ManualRecordStatusRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.ManualRecordStatusResponse.SerializeToString,
            ),
            'StartRecorders': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRecorders,
                    request_deserializer=api_dot_onyx__pb2.StartRecordersRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.StartRecordersResponse.SerializeToString,
            ),
            'StopRecorders': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRecorders,
                    request_deserializer=api_dot_onyx__pb2.StopRecordersRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.StopRecordersResponse.SerializeToString,
            ),
            'GetRecordersStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecordersStatus,
                    request_deserializer=api_dot_onyx__pb2.GetRecordersStatusRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.GetRecordersStatusResponse.SerializeToString,
            ),
            'GetModuleConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModuleConfig,
                    request_deserializer=api_dot_onyx__pb2.GetModuleConfigRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.GetModuleConfigResponse.SerializeToString,
            ),
            'SetModuleConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetModuleConfig,
                    request_deserializer=api_dot_onyx__pb2.SetModuleConfigRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.SetModuleConfigResponse.SerializeToString,
            ),
            'ControlPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlPlaylist,
                    request_deserializer=api_dot_onyx__pb2.ControlPlaylistRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.ControlPlaylistResponse.SerializeToString,
            ),
            'GetPlaylistStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistStatus,
                    request_deserializer=api_dot_onyx__pb2.GetPlaylistStatusRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.GetPlaylistStatusResponse.SerializeToString,
            ),
            'GetSystemBackups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemBackups,
                    request_deserializer=common_dot_common__pb2.GetSystemBackupsRequest.FromString,
                    response_serializer=common_dot_common__pb2.GetSystemBackupsResponse.SerializeToString,
            ),
            'DeleteBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBackup,
                    request_deserializer=api_dot_onyx__pb2.DeleteBackupRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.DeleteBackupResponse.SerializeToString,
            ),
            'DownloadBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadBackup,
                    request_deserializer=api_dot_onyx__pb2.DownloadBackupRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.DownloadBackupResponse.SerializeToString,
            ),
            'ManualBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.ManualBackup,
                    request_deserializer=api_dot_onyx__pb2.ManualBackupRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.ManualBackupResponse.SerializeToString,
            ),
            'GetManualBackupStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManualBackupStatus,
                    request_deserializer=api_dot_onyx__pb2.GetManualBackupStatusRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.GetManualBackupStatusResponse.SerializeToString,
            ),
            'TriggerDataBaseStatsCleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerDataBaseStatsCleanup,
                    request_deserializer=api_dot_onyx__pb2.TriggerDataBaseStatsCleanupRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.TriggerDataBaseStatsCleanupResponse.SerializeToString,
            ),
            'StreamDetections': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDetections,
                    request_deserializer=api_dot_onyx__pb2.StreamDetectionsRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.StreamDetectionsResponse.SerializeToString,
            ),
            'GetTimeseriesSources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeseriesSources,
                    request_deserializer=api_dot_onyx__pb2.GetTimeseriesSourcesRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.GetTimeseriesSourcesResponse.SerializeToString,
            ),
            'GetTimeseries': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTimeseries,
                    request_deserializer=api_dot_onyx__pb2.GetTimeseriesRequest.FromString,
                    response_serializer=common_dot_common__pb2.TimeseriesPacket.SerializeToString,
            ),
            'StreamTimeseries': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTimeseries,
                    request_deserializer=api_dot_onyx__pb2.StreamTimeseriesRequest.FromString,
                    response_serializer=common_dot_common__pb2.TimeseriesPacket.SerializeToString,
            ),
            'StreamTimeseriesOut': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTimeseriesOut,
                    request_deserializer=api_dot_onyx__pb2.StreamTimeseriesOutRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.StreamTimeseriesOutResponse.SerializeToString,
            ),
            'StreamTimeseriesIn': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTimeseriesIn,
                    request_deserializer=api_dot_onyx__pb2.StreamTimeseriesInRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.StreamTimeseriesInResponse.SerializeToString,
            ),
            'GetFiberLength': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFiberLength,
                    request_deserializer=api_dot_onyx__pb2.FiberLengthRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.FiberLengthResponse.SerializeToString,
            ),
            'GetChainStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChainStatus,
                    request_deserializer=api_dot_onyx__pb2.ChainStatusRequest.FromString,
                    response_serializer=api_dot_onyx__pb2.ChainStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.Onyx', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.Onyx', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Onyx(object):
    """Protobuf specification for Onyx gRPC API.
    Note that in general there are two instances of the Onyx software running
    on a device. Once for Fiber 1 and one for Fiber2.
    Call the API on the correct software instance to get interact with one fiber
    or the other.
    --------------------------------------------------------------------------
    Data Extraction:
    """

    @staticmethod
    def Extract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/Extract',
            api_dot_onyx__pb2.ExtractionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelExtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/CancelExtract',
            api_dot_onyx__pb2.CancelExtractionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/ExtractStatus',
            api_dot_onyx__pb2.ExtractionStatusRequest.SerializeToString,
            api_dot_onyx__pb2.ExtractionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractStatuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/ExtractStatuses',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            api_dot_onyx__pb2.ExtractionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAWSCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/SetAWSCredentials',
            api_dot_onyx__pb2.NamedAWSCredentials.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfigurationBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetConfigurationBackup',
            api_dot_onyx__pb2.BackupRequest.SerializeToString,
            api_dot_onyx__pb2.BackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/RestoreConfiguration',
            api_dot_onyx__pb2.RestoreRequest.SerializeToString,
            api_dot_onyx__pb2.RestoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAcquisitionStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetAcquisitionStats',
            api_dot_onyx__pb2.AcquisitionStatsRequest.SerializeToString,
            api_dot_onyx__pb2.AcquisitionStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeAllSysEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/AcknowledgeAllSysEvents',
            api_dot_onyx__pb2.AcknowledgeAllSysEventsRequest.SerializeToString,
            api_dot_onyx__pb2.AcknowledgeAllSysEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatusSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetSystemStatusSummary',
            api_dot_onyx__pb2.SystemStatusSummaryRequest.SerializeToString,
            api_dot_onyx__pb2.SystemStatusSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetSystemStatus',
            api_dot_onyx__pb2.SystemStatusRequest.SerializeToString,
            api_dot_onyx__pb2.SystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetSystemEvents',
            api_dot_onyx__pb2.SystemEventsRequest.SerializeToString,
            api_dot_onyx__pb2.SystemEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReportableSystemEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetReportableSystemEvents',
            api_dot_onyx__pb2.ReportableSystemEventsRequest.SerializeToString,
            api_dot_onyx__pb2.ReportableSystemEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOnyxSoftwareStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetOnyxSoftwareStatus',
            api_dot_onyx__pb2.OnyxSoftwareStatusRequest.SerializeToString,
            api_dot_onyx__pb2.OnyxSoftwareStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDetections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetDetections',
            api_dot_onyx__pb2.DetectionsRequest.SerializeToString,
            api_dot_onyx__pb2.DetectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIdentification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetIdentification',
            api_dot_onyx__pb2.IdentificationRequest.SerializeToString,
            api_dot_onyx__pb2.IdentificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartManualRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/StartManualRecord',
            api_dot_onyx__pb2.StartManualRecordRequest.SerializeToString,
            api_dot_onyx__pb2.StartManualRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopManualRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/StopManualRecord',
            api_dot_onyx__pb2.StopManualRecordingRequest.SerializeToString,
            api_dot_onyx__pb2.StopManualRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManualRecordStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/ManualRecordStatus',
            api_dot_onyx__pb2.ManualRecordStatusRequest.SerializeToString,
            api_dot_onyx__pb2.ManualRecordStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRecorders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/StartRecorders',
            api_dot_onyx__pb2.StartRecordersRequest.SerializeToString,
            api_dot_onyx__pb2.StartRecordersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRecorders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/StopRecorders',
            api_dot_onyx__pb2.StopRecordersRequest.SerializeToString,
            api_dot_onyx__pb2.StopRecordersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecordersStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetRecordersStatus',
            api_dot_onyx__pb2.GetRecordersStatusRequest.SerializeToString,
            api_dot_onyx__pb2.GetRecordersStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModuleConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetModuleConfig',
            api_dot_onyx__pb2.GetModuleConfigRequest.SerializeToString,
            api_dot_onyx__pb2.GetModuleConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetModuleConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/SetModuleConfig',
            api_dot_onyx__pb2.SetModuleConfigRequest.SerializeToString,
            api_dot_onyx__pb2.SetModuleConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/ControlPlaylist',
            api_dot_onyx__pb2.ControlPlaylistRequest.SerializeToString,
            api_dot_onyx__pb2.ControlPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetPlaylistStatus',
            api_dot_onyx__pb2.GetPlaylistStatusRequest.SerializeToString,
            api_dot_onyx__pb2.GetPlaylistStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemBackups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetSystemBackups',
            common_dot_common__pb2.GetSystemBackupsRequest.SerializeToString,
            common_dot_common__pb2.GetSystemBackupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/DeleteBackup',
            api_dot_onyx__pb2.DeleteBackupRequest.SerializeToString,
            api_dot_onyx__pb2.DeleteBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/DownloadBackup',
            api_dot_onyx__pb2.DownloadBackupRequest.SerializeToString,
            api_dot_onyx__pb2.DownloadBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManualBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/ManualBackup',
            api_dot_onyx__pb2.ManualBackupRequest.SerializeToString,
            api_dot_onyx__pb2.ManualBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetManualBackupStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetManualBackupStatus',
            api_dot_onyx__pb2.GetManualBackupStatusRequest.SerializeToString,
            api_dot_onyx__pb2.GetManualBackupStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerDataBaseStatsCleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/TriggerDataBaseStatsCleanup',
            api_dot_onyx__pb2.TriggerDataBaseStatsCleanupRequest.SerializeToString,
            api_dot_onyx__pb2.TriggerDataBaseStatsCleanupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDetections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.Onyx/StreamDetections',
            api_dot_onyx__pb2.StreamDetectionsRequest.SerializeToString,
            api_dot_onyx__pb2.StreamDetectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimeseriesSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetTimeseriesSources',
            api_dot_onyx__pb2.GetTimeseriesSourcesRequest.SerializeToString,
            api_dot_onyx__pb2.GetTimeseriesSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimeseries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.Onyx/GetTimeseries',
            api_dot_onyx__pb2.GetTimeseriesRequest.SerializeToString,
            common_dot_common__pb2.TimeseriesPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTimeseries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.Onyx/StreamTimeseries',
            api_dot_onyx__pb2.StreamTimeseriesRequest.SerializeToString,
            common_dot_common__pb2.TimeseriesPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTimeseriesOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.Onyx/StreamTimeseriesOut',
            api_dot_onyx__pb2.StreamTimeseriesOutRequest.SerializeToString,
            api_dot_onyx__pb2.StreamTimeseriesOutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTimeseriesIn(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/api.Onyx/StreamTimeseriesIn',
            api_dot_onyx__pb2.StreamTimeseriesInRequest.SerializeToString,
            api_dot_onyx__pb2.StreamTimeseriesInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFiberLength(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetFiberLength',
            api_dot_onyx__pb2.FiberLengthRequest.SerializeToString,
            api_dot_onyx__pb2.FiberLengthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChainStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.Onyx/GetChainStatus',
            api_dot_onyx__pb2.ChainStatusRequest.SerializeToString,
            api_dot_onyx__pb2.ChainStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

