"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Service specification for the Onyx Public API, a gRPC API. 

For example clients see:
- cmd/grpc_client/grpc_client.go - an command-line client that demonstrates
- cmd/backuprestore
how to build a client;
- documentation: https://sintela.atlassian.net/l/cp/j0ukrw3Q.
"""

from api import onyx_pb2 as _onyx_pb2
from collections import abc as _abc
from common import common_pb2 as _common_pb2
from google.protobuf import empty_pb2 as _empty_pb2
from grpc import aio as _aio
import abc as _abc_1
import builtins as _builtins
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class OnyxStub:
    """Protobuf specification for Onyx gRPC API.
    Note that in general there are two instances of the Onyx software running
    on a device. Once for Fiber 1 and one for Fiber2.
    Call the API on the correct software instance to get interact with one fiber
    or the other.
    --------------------------------------------------------------------------
    Data Extraction:
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> OnyxAsyncStub: ...
    Extract: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.ExtractionRequest, _empty_pb2.Empty]
    """Submit a data extraction request. This can fail if the server's queue for
    data extractions is full. This return as soon as the request has been
    submitted; it does not wait for the extraction process to complete.
    To check on progress and success/failure, use the ExtractStatus RPC.
    """
    CancelExtract: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.CancelExtractionRequest, _empty_pb2.Empty]
    """Request cancellation of a data extraction, and succeeds even if no such
    data extraction job currently exists.
    """
    ExtractStatus: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.ExtractionStatusRequest, _onyx_pb2.ExtractionStatusResponse]
    """Request the status of a current or recent extraction requests by ID."""
    ExtractStatuses: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _onyx_pb2.ExtractionStatusResponse]
    """Request the status of all current and recent extraction requests."""
    SetAWSCredentials: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.NamedAWSCredentials, _empty_pb2.Empty]
    """Set the AWS Credentials to be used for subsequent AWS access, e.g. data
    extractions to S3 buckets.
    """
    GetConfigurationBackup: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.BackupRequest, _onyx_pb2.BackupResponse]
    """GetConfigurationBackup() returns the configuration backup as a JSON string"""
    RestoreConfiguration: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.RestoreRequest, _onyx_pb2.RestoreResponse]
    """RestoreConfiguration() retores the configuration for a system"""
    GetAcquisitionStats: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.AcquisitionStatsRequest, _onyx_pb2.AcquisitionStatsResponse]
    """GetAcquisitionStats returns the current acquisition settings of the system
    This acquisition details can de different for each fiber. Call this service
    on the fiber you are interested in, e.g. onyx software instance 1 or 2
    """
    AcknowledgeAllSysEvents: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.AcknowledgeAllSysEventsRequest, _onyx_pb2.AcknowledgeAllSysEventsResponse]
    """AcknowledgeAllSysEvents acknowledges all the system events
    present on the node on which it was called. The user requires the
    ManageEvents permission to make a valid call.
    """
    GetSystemStatusSummary: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.SystemStatusSummaryRequest, _onyx_pb2.SystemStatusSummaryResponse]
    """GetSystemStatusSummary returns a top level summary of the system status
    This includes an overall status for disks, temperatures, database etc.
    Use the GetSystemStatus to drill into these areas for further information.
    """
    GetSystemStatus: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.SystemStatusRequest, _onyx_pb2.SystemStatusResponse]
    """GetSystemStatus returns the status of the system.
    Status includes temperatures, cpu load, disk usage, etc.
    """
    GetSystemEvents: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.SystemEventsRequest, _onyx_pb2.SystemEventsResponse]
    """GetSystemEvents returns a list of system events. System Events are
    errors or information messages about the state of the system.
    If the system is behaving normally there should be no error level
    events reported.
    Examples of Error Events:
    - Data not flowing
    - Disk Full
    - Over Temperature
    Example of Information Events:
    - System Configuration Changed
    - Event output temporarily disabled
    """
    GetReportableSystemEvents: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.ReportableSystemEventsRequest, _onyx_pb2.ReportableSystemEventsResponse]
    """GetReportableSystemEvents returns a list of reportable system events.
    Reportable events are important events that have been in a bad status for
    a period of time. Important events include, FiberBreak, DataNotFlowing,
    DiskFull, etc.
    """
    GetOnyxSoftwareStatus: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.OnyxSoftwareStatusRequest, _onyx_pb2.OnyxSoftwareStatusResponse]
    """GetOnyxSoftwareStatus returns the status of the Onyx software.
    Normally an Onyx system runs two instances of the software,
    one for each fiber. Status includes software uptime, sensor data uptime,
    software version etc.
    """
    GetDetections: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.DetectionsRequest, _onyx_pb2.DetectionsResponse]
    """GetDetections returns a list of detections that have been made
    by the system. Each detection includes it's time, classification
    and position.
    """
    GetIdentification: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.IdentificationRequest, _onyx_pb2.IdentificationResponse]
    """-------------------------------------------------------------------------
    GetIdentification returns information that can be used to identify a system
    """
    StartManualRecord: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.StartManualRecordRequest, _onyx_pb2.StartManualRecordResponse]
    """StartManualRecord starts the manual recorder for timeseries data"""
    StopManualRecord: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.StopManualRecordingRequest, _onyx_pb2.StopManualRecordingResponse]
    """StopManualRecord stops the manual recorder"""
    ManualRecordStatus: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.ManualRecordStatusRequest, _onyx_pb2.ManualRecordStatusResponse]
    """GetRecordersStatus return the status of the manual recorder"""
    StartRecorders: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.StartRecordersRequest, _onyx_pb2.StartRecordersResponse]
    """StartRecorders starts all the recorders recording to the given path"""
    StopRecorders: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.StopRecordersRequest, _onyx_pb2.StopRecordersResponse]
    """StopRecorders stops all the recorders recording"""
    GetRecordersStatus: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.GetRecordersStatusRequest, _onyx_pb2.GetRecordersStatusResponse]
    """GetRecordersStatus return the status of the recorders"""
    GetModuleConfig: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.GetModuleConfigRequest, _onyx_pb2.GetModuleConfigResponse]
    """GetModuleConfig returns the configuration of an available 
    module in the module registry
    """
    SetModuleConfig: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.SetModuleConfigRequest, _onyx_pb2.SetModuleConfigResponse]
    """SetModuleConfig sets the configuration of a module"""
    ControlPlaylist: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.ControlPlaylistRequest, _onyx_pb2.ControlPlaylistResponse]
    """ControlPlaylist is used to control playlist replay"""
    GetPlaylistStatus: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.GetPlaylistStatusRequest, _onyx_pb2.GetPlaylistStatusResponse]
    """GetPlaylistStatus returns the status of the playlist replay.
    The replay can include the list of recordings in the selected playlist.
    """
    GetSystemBackups: _grpc.UnaryUnaryMultiCallable[_common_pb2.GetSystemBackupsRequest, _common_pb2.GetSystemBackupsResponse]
    """GetSystemBackups returns the systems local and portal backups"""
    DeleteBackup: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.DeleteBackupRequest, _onyx_pb2.DeleteBackupResponse]
    """DeleteBackup deletes the chosen backup from the system"""
    DownloadBackup: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.DownloadBackupRequest, _onyx_pb2.DownloadBackupResponse]
    """DownloadBackup returns content of a system backup"""
    ManualBackup: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.ManualBackupRequest, _onyx_pb2.ManualBackupResponse]
    """ManualBackup prompts the system to manually backup"""
    GetManualBackupStatus: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.GetManualBackupStatusRequest, _onyx_pb2.GetManualBackupStatusResponse]
    """GetManualBackupStatus gets status of manual backup"""
    TriggerDataBaseStatsCleanup: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.TriggerDataBaseStatsCleanupRequest, _onyx_pb2.TriggerDataBaseStatsCleanupResponse]
    """TriggerDataBaseStatsCleanup triggers the cleanup of the database stats
    This normally runs on a schedule but calling this will trigger it to run
    """
    StreamDetections: _grpc.UnaryStreamMultiCallable[_onyx_pb2.StreamDetectionsRequest, _onyx_pb2.StreamDetectionsResponse]
    """StreamDetections requests a stream of events from the server
    This publishes detected events to the stream as they arrive in
    the event store
    """
    GetTimeseriesSources: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.GetTimeseriesSourcesRequest, _onyx_pb2.GetTimeseriesSourcesResponse]
    """GetTimeseriesSources returns the list of timeseries sources that are
    available for streaming with the GetTimeSeries service.
    """
    @_builtins.property
    @_deprecated("""This method has been marked as deprecated using proto method options.""")
    def GetTimeseries(self) -> _grpc.UnaryStreamMultiCallable[_onyx_pb2.GetTimeseriesRequest, _common_pb2.TimeseriesPacket]:
        """GetTimeseries streams timeseries data from the given source.
        Deprecated: Use StreamTimeseriesOut instead.
        """
    @_builtins.property
    @_deprecated("""This method has been marked as deprecated using proto method options.""")
    def StreamTimeseries(self) -> _grpc.UnaryStreamMultiCallable[_onyx_pb2.StreamTimeseriesRequest, _common_pb2.TimeseriesPacket]:
        """StreamTimeseries streams timeseries data from the given source.
        Deprecated: Use StreamTimeseriesOut instead.
        """
    StreamTimeseriesOut: _grpc.UnaryStreamMultiCallable[_onyx_pb2.StreamTimeseriesOutRequest, _onyx_pb2.StreamTimeseriesOutResponse]
    """Stream timeseries packets out from the given source."""
    StreamTimeseriesIn: _grpc.StreamUnaryMultiCallable[_onyx_pb2.StreamTimeseriesInRequest, _onyx_pb2.StreamTimeseriesInResponse]
    """StreamTimeseriesIn streams timeseries data into the given sink."""
    GetFiberLength: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.FiberLengthRequest, _onyx_pb2.FiberLengthResponse]
    """GetFiberLength returns the length of the fiber for a given FiberNumber"""
    GetChainStatus: _grpc.UnaryUnaryMultiCallable[_onyx_pb2.ChainStatusRequest, _onyx_pb2.ChainStatusResponse]
    """GetChainStatus returns the name of the current chain and if it is unsaved"""

@_typing.type_check_only
class OnyxAsyncStub(OnyxStub):
    """Protobuf specification for Onyx gRPC API.
    Note that in general there are two instances of the Onyx software running
    on a device. Once for Fiber 1 and one for Fiber2.
    Call the API on the correct software instance to get interact with one fiber
    or the other.
    --------------------------------------------------------------------------
    Data Extraction:
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Extract: _aio.UnaryUnaryMultiCallable[_onyx_pb2.ExtractionRequest, _empty_pb2.Empty]  # type: ignore[assignment]
    """Submit a data extraction request. This can fail if the server's queue for
    data extractions is full. This return as soon as the request has been
    submitted; it does not wait for the extraction process to complete.
    To check on progress and success/failure, use the ExtractStatus RPC.
    """
    CancelExtract: _aio.UnaryUnaryMultiCallable[_onyx_pb2.CancelExtractionRequest, _empty_pb2.Empty]  # type: ignore[assignment]
    """Request cancellation of a data extraction, and succeeds even if no such
    data extraction job currently exists.
    """
    ExtractStatus: _aio.UnaryUnaryMultiCallable[_onyx_pb2.ExtractionStatusRequest, _onyx_pb2.ExtractionStatusResponse]  # type: ignore[assignment]
    """Request the status of a current or recent extraction requests by ID."""
    ExtractStatuses: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _onyx_pb2.ExtractionStatusResponse]  # type: ignore[assignment]
    """Request the status of all current and recent extraction requests."""
    SetAWSCredentials: _aio.UnaryUnaryMultiCallable[_onyx_pb2.NamedAWSCredentials, _empty_pb2.Empty]  # type: ignore[assignment]
    """Set the AWS Credentials to be used for subsequent AWS access, e.g. data
    extractions to S3 buckets.
    """
    GetConfigurationBackup: _aio.UnaryUnaryMultiCallable[_onyx_pb2.BackupRequest, _onyx_pb2.BackupResponse]  # type: ignore[assignment]
    """GetConfigurationBackup() returns the configuration backup as a JSON string"""
    RestoreConfiguration: _aio.UnaryUnaryMultiCallable[_onyx_pb2.RestoreRequest, _onyx_pb2.RestoreResponse]  # type: ignore[assignment]
    """RestoreConfiguration() retores the configuration for a system"""
    GetAcquisitionStats: _aio.UnaryUnaryMultiCallable[_onyx_pb2.AcquisitionStatsRequest, _onyx_pb2.AcquisitionStatsResponse]  # type: ignore[assignment]
    """GetAcquisitionStats returns the current acquisition settings of the system
    This acquisition details can de different for each fiber. Call this service
    on the fiber you are interested in, e.g. onyx software instance 1 or 2
    """
    AcknowledgeAllSysEvents: _aio.UnaryUnaryMultiCallable[_onyx_pb2.AcknowledgeAllSysEventsRequest, _onyx_pb2.AcknowledgeAllSysEventsResponse]  # type: ignore[assignment]
    """AcknowledgeAllSysEvents acknowledges all the system events
    present on the node on which it was called. The user requires the
    ManageEvents permission to make a valid call.
    """
    GetSystemStatusSummary: _aio.UnaryUnaryMultiCallable[_onyx_pb2.SystemStatusSummaryRequest, _onyx_pb2.SystemStatusSummaryResponse]  # type: ignore[assignment]
    """GetSystemStatusSummary returns a top level summary of the system status
    This includes an overall status for disks, temperatures, database etc.
    Use the GetSystemStatus to drill into these areas for further information.
    """
    GetSystemStatus: _aio.UnaryUnaryMultiCallable[_onyx_pb2.SystemStatusRequest, _onyx_pb2.SystemStatusResponse]  # type: ignore[assignment]
    """GetSystemStatus returns the status of the system.
    Status includes temperatures, cpu load, disk usage, etc.
    """
    GetSystemEvents: _aio.UnaryUnaryMultiCallable[_onyx_pb2.SystemEventsRequest, _onyx_pb2.SystemEventsResponse]  # type: ignore[assignment]
    """GetSystemEvents returns a list of system events. System Events are
    errors or information messages about the state of the system.
    If the system is behaving normally there should be no error level
    events reported.
    Examples of Error Events:
    - Data not flowing
    - Disk Full
    - Over Temperature
    Example of Information Events:
    - System Configuration Changed
    - Event output temporarily disabled
    """
    GetReportableSystemEvents: _aio.UnaryUnaryMultiCallable[_onyx_pb2.ReportableSystemEventsRequest, _onyx_pb2.ReportableSystemEventsResponse]  # type: ignore[assignment]
    """GetReportableSystemEvents returns a list of reportable system events.
    Reportable events are important events that have been in a bad status for
    a period of time. Important events include, FiberBreak, DataNotFlowing,
    DiskFull, etc.
    """
    GetOnyxSoftwareStatus: _aio.UnaryUnaryMultiCallable[_onyx_pb2.OnyxSoftwareStatusRequest, _onyx_pb2.OnyxSoftwareStatusResponse]  # type: ignore[assignment]
    """GetOnyxSoftwareStatus returns the status of the Onyx software.
    Normally an Onyx system runs two instances of the software,
    one for each fiber. Status includes software uptime, sensor data uptime,
    software version etc.
    """
    GetDetections: _aio.UnaryUnaryMultiCallable[_onyx_pb2.DetectionsRequest, _onyx_pb2.DetectionsResponse]  # type: ignore[assignment]
    """GetDetections returns a list of detections that have been made
    by the system. Each detection includes it's time, classification
    and position.
    """
    GetIdentification: _aio.UnaryUnaryMultiCallable[_onyx_pb2.IdentificationRequest, _onyx_pb2.IdentificationResponse]  # type: ignore[assignment]
    """-------------------------------------------------------------------------
    GetIdentification returns information that can be used to identify a system
    """
    StartManualRecord: _aio.UnaryUnaryMultiCallable[_onyx_pb2.StartManualRecordRequest, _onyx_pb2.StartManualRecordResponse]  # type: ignore[assignment]
    """StartManualRecord starts the manual recorder for timeseries data"""
    StopManualRecord: _aio.UnaryUnaryMultiCallable[_onyx_pb2.StopManualRecordingRequest, _onyx_pb2.StopManualRecordingResponse]  # type: ignore[assignment]
    """StopManualRecord stops the manual recorder"""
    ManualRecordStatus: _aio.UnaryUnaryMultiCallable[_onyx_pb2.ManualRecordStatusRequest, _onyx_pb2.ManualRecordStatusResponse]  # type: ignore[assignment]
    """GetRecordersStatus return the status of the manual recorder"""
    StartRecorders: _aio.UnaryUnaryMultiCallable[_onyx_pb2.StartRecordersRequest, _onyx_pb2.StartRecordersResponse]  # type: ignore[assignment]
    """StartRecorders starts all the recorders recording to the given path"""
    StopRecorders: _aio.UnaryUnaryMultiCallable[_onyx_pb2.StopRecordersRequest, _onyx_pb2.StopRecordersResponse]  # type: ignore[assignment]
    """StopRecorders stops all the recorders recording"""
    GetRecordersStatus: _aio.UnaryUnaryMultiCallable[_onyx_pb2.GetRecordersStatusRequest, _onyx_pb2.GetRecordersStatusResponse]  # type: ignore[assignment]
    """GetRecordersStatus return the status of the recorders"""
    GetModuleConfig: _aio.UnaryUnaryMultiCallable[_onyx_pb2.GetModuleConfigRequest, _onyx_pb2.GetModuleConfigResponse]  # type: ignore[assignment]
    """GetModuleConfig returns the configuration of an available 
    module in the module registry
    """
    SetModuleConfig: _aio.UnaryUnaryMultiCallable[_onyx_pb2.SetModuleConfigRequest, _onyx_pb2.SetModuleConfigResponse]  # type: ignore[assignment]
    """SetModuleConfig sets the configuration of a module"""
    ControlPlaylist: _aio.UnaryUnaryMultiCallable[_onyx_pb2.ControlPlaylistRequest, _onyx_pb2.ControlPlaylistResponse]  # type: ignore[assignment]
    """ControlPlaylist is used to control playlist replay"""
    GetPlaylistStatus: _aio.UnaryUnaryMultiCallable[_onyx_pb2.GetPlaylistStatusRequest, _onyx_pb2.GetPlaylistStatusResponse]  # type: ignore[assignment]
    """GetPlaylistStatus returns the status of the playlist replay.
    The replay can include the list of recordings in the selected playlist.
    """
    GetSystemBackups: _aio.UnaryUnaryMultiCallable[_common_pb2.GetSystemBackupsRequest, _common_pb2.GetSystemBackupsResponse]  # type: ignore[assignment]
    """GetSystemBackups returns the systems local and portal backups"""
    DeleteBackup: _aio.UnaryUnaryMultiCallable[_onyx_pb2.DeleteBackupRequest, _onyx_pb2.DeleteBackupResponse]  # type: ignore[assignment]
    """DeleteBackup deletes the chosen backup from the system"""
    DownloadBackup: _aio.UnaryUnaryMultiCallable[_onyx_pb2.DownloadBackupRequest, _onyx_pb2.DownloadBackupResponse]  # type: ignore[assignment]
    """DownloadBackup returns content of a system backup"""
    ManualBackup: _aio.UnaryUnaryMultiCallable[_onyx_pb2.ManualBackupRequest, _onyx_pb2.ManualBackupResponse]  # type: ignore[assignment]
    """ManualBackup prompts the system to manually backup"""
    GetManualBackupStatus: _aio.UnaryUnaryMultiCallable[_onyx_pb2.GetManualBackupStatusRequest, _onyx_pb2.GetManualBackupStatusResponse]  # type: ignore[assignment]
    """GetManualBackupStatus gets status of manual backup"""
    TriggerDataBaseStatsCleanup: _aio.UnaryUnaryMultiCallable[_onyx_pb2.TriggerDataBaseStatsCleanupRequest, _onyx_pb2.TriggerDataBaseStatsCleanupResponse]  # type: ignore[assignment]
    """TriggerDataBaseStatsCleanup triggers the cleanup of the database stats
    This normally runs on a schedule but calling this will trigger it to run
    """
    StreamDetections: _aio.UnaryStreamMultiCallable[_onyx_pb2.StreamDetectionsRequest, _onyx_pb2.StreamDetectionsResponse]  # type: ignore[assignment]
    """StreamDetections requests a stream of events from the server
    This publishes detected events to the stream as they arrive in
    the event store
    """
    GetTimeseriesSources: _aio.UnaryUnaryMultiCallable[_onyx_pb2.GetTimeseriesSourcesRequest, _onyx_pb2.GetTimeseriesSourcesResponse]  # type: ignore[assignment]
    """GetTimeseriesSources returns the list of timeseries sources that are
    available for streaming with the GetTimeSeries service.
    """
    @_builtins.property
    @_deprecated("""This method has been marked as deprecated using proto method options.""")
    def GetTimeseries(self) -> _aio.UnaryStreamMultiCallable[_onyx_pb2.GetTimeseriesRequest, _common_pb2.TimeseriesPacket]:  # type: ignore[override]
        """GetTimeseries streams timeseries data from the given source.
        Deprecated: Use StreamTimeseriesOut instead.
        """
    @_builtins.property
    @_deprecated("""This method has been marked as deprecated using proto method options.""")
    def StreamTimeseries(self) -> _aio.UnaryStreamMultiCallable[_onyx_pb2.StreamTimeseriesRequest, _common_pb2.TimeseriesPacket]:  # type: ignore[override]
        """StreamTimeseries streams timeseries data from the given source.
        Deprecated: Use StreamTimeseriesOut instead.
        """
    StreamTimeseriesOut: _aio.UnaryStreamMultiCallable[_onyx_pb2.StreamTimeseriesOutRequest, _onyx_pb2.StreamTimeseriesOutResponse]  # type: ignore[assignment]
    """Stream timeseries packets out from the given source."""
    StreamTimeseriesIn: _aio.StreamUnaryMultiCallable[_onyx_pb2.StreamTimeseriesInRequest, _onyx_pb2.StreamTimeseriesInResponse]  # type: ignore[assignment]
    """StreamTimeseriesIn streams timeseries data into the given sink."""
    GetFiberLength: _aio.UnaryUnaryMultiCallable[_onyx_pb2.FiberLengthRequest, _onyx_pb2.FiberLengthResponse]  # type: ignore[assignment]
    """GetFiberLength returns the length of the fiber for a given FiberNumber"""
    GetChainStatus: _aio.UnaryUnaryMultiCallable[_onyx_pb2.ChainStatusRequest, _onyx_pb2.ChainStatusResponse]  # type: ignore[assignment]
    """GetChainStatus returns the name of the current chain and if it is unsaved"""

class OnyxServicer(metaclass=_abc_1.ABCMeta):
    """Protobuf specification for Onyx gRPC API.
    Note that in general there are two instances of the Onyx software running
    on a device. Once for Fiber 1 and one for Fiber2.
    Call the API on the correct software instance to get interact with one fiber
    or the other.
    --------------------------------------------------------------------------
    Data Extraction:
    """

    @_abc_1.abstractmethod
    def Extract(
        self,
        request: _onyx_pb2.ExtractionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_empty_pb2.Empty, _abc.Awaitable[_empty_pb2.Empty]]:
        """Submit a data extraction request. This can fail if the server's queue for
        data extractions is full. This return as soon as the request has been
        submitted; it does not wait for the extraction process to complete.
        To check on progress and success/failure, use the ExtractStatus RPC.
        """

    @_abc_1.abstractmethod
    def CancelExtract(
        self,
        request: _onyx_pb2.CancelExtractionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_empty_pb2.Empty, _abc.Awaitable[_empty_pb2.Empty]]:
        """Request cancellation of a data extraction, and succeeds even if no such
        data extraction job currently exists.
        """

    @_abc_1.abstractmethod
    def ExtractStatus(
        self,
        request: _onyx_pb2.ExtractionStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.ExtractionStatusResponse, _abc.Awaitable[_onyx_pb2.ExtractionStatusResponse]]:
        """Request the status of a current or recent extraction requests by ID."""

    @_abc_1.abstractmethod
    def ExtractStatuses(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.ExtractionStatusResponse, _abc.Awaitable[_onyx_pb2.ExtractionStatusResponse]]:
        """Request the status of all current and recent extraction requests."""

    @_abc_1.abstractmethod
    def SetAWSCredentials(
        self,
        request: _onyx_pb2.NamedAWSCredentials,
        context: _ServicerContext,
    ) -> _typing.Union[_empty_pb2.Empty, _abc.Awaitable[_empty_pb2.Empty]]:
        """Set the AWS Credentials to be used for subsequent AWS access, e.g. data
        extractions to S3 buckets.
        """

    @_abc_1.abstractmethod
    def GetConfigurationBackup(
        self,
        request: _onyx_pb2.BackupRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.BackupResponse, _abc.Awaitable[_onyx_pb2.BackupResponse]]:
        """GetConfigurationBackup() returns the configuration backup as a JSON string"""

    @_abc_1.abstractmethod
    def RestoreConfiguration(
        self,
        request: _onyx_pb2.RestoreRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.RestoreResponse, _abc.Awaitable[_onyx_pb2.RestoreResponse]]:
        """RestoreConfiguration() retores the configuration for a system"""

    @_abc_1.abstractmethod
    def GetAcquisitionStats(
        self,
        request: _onyx_pb2.AcquisitionStatsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.AcquisitionStatsResponse, _abc.Awaitable[_onyx_pb2.AcquisitionStatsResponse]]:
        """GetAcquisitionStats returns the current acquisition settings of the system
        This acquisition details can de different for each fiber. Call this service
        on the fiber you are interested in, e.g. onyx software instance 1 or 2
        """

    @_abc_1.abstractmethod
    def AcknowledgeAllSysEvents(
        self,
        request: _onyx_pb2.AcknowledgeAllSysEventsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.AcknowledgeAllSysEventsResponse, _abc.Awaitable[_onyx_pb2.AcknowledgeAllSysEventsResponse]]:
        """AcknowledgeAllSysEvents acknowledges all the system events
        present on the node on which it was called. The user requires the
        ManageEvents permission to make a valid call.
        """

    @_abc_1.abstractmethod
    def GetSystemStatusSummary(
        self,
        request: _onyx_pb2.SystemStatusSummaryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.SystemStatusSummaryResponse, _abc.Awaitable[_onyx_pb2.SystemStatusSummaryResponse]]:
        """GetSystemStatusSummary returns a top level summary of the system status
        This includes an overall status for disks, temperatures, database etc.
        Use the GetSystemStatus to drill into these areas for further information.
        """

    @_abc_1.abstractmethod
    def GetSystemStatus(
        self,
        request: _onyx_pb2.SystemStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.SystemStatusResponse, _abc.Awaitable[_onyx_pb2.SystemStatusResponse]]:
        """GetSystemStatus returns the status of the system.
        Status includes temperatures, cpu load, disk usage, etc.
        """

    @_abc_1.abstractmethod
    def GetSystemEvents(
        self,
        request: _onyx_pb2.SystemEventsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.SystemEventsResponse, _abc.Awaitable[_onyx_pb2.SystemEventsResponse]]:
        """GetSystemEvents returns a list of system events. System Events are
        errors or information messages about the state of the system.
        If the system is behaving normally there should be no error level
        events reported.
        Examples of Error Events:
        - Data not flowing
        - Disk Full
        - Over Temperature
        Example of Information Events:
        - System Configuration Changed
        - Event output temporarily disabled
        """

    @_abc_1.abstractmethod
    def GetReportableSystemEvents(
        self,
        request: _onyx_pb2.ReportableSystemEventsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.ReportableSystemEventsResponse, _abc.Awaitable[_onyx_pb2.ReportableSystemEventsResponse]]:
        """GetReportableSystemEvents returns a list of reportable system events.
        Reportable events are important events that have been in a bad status for
        a period of time. Important events include, FiberBreak, DataNotFlowing,
        DiskFull, etc.
        """

    @_abc_1.abstractmethod
    def GetOnyxSoftwareStatus(
        self,
        request: _onyx_pb2.OnyxSoftwareStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.OnyxSoftwareStatusResponse, _abc.Awaitable[_onyx_pb2.OnyxSoftwareStatusResponse]]:
        """GetOnyxSoftwareStatus returns the status of the Onyx software.
        Normally an Onyx system runs two instances of the software,
        one for each fiber. Status includes software uptime, sensor data uptime,
        software version etc.
        """

    @_abc_1.abstractmethod
    def GetDetections(
        self,
        request: _onyx_pb2.DetectionsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.DetectionsResponse, _abc.Awaitable[_onyx_pb2.DetectionsResponse]]:
        """GetDetections returns a list of detections that have been made
        by the system. Each detection includes it's time, classification
        and position.
        """

    @_abc_1.abstractmethod
    def GetIdentification(
        self,
        request: _onyx_pb2.IdentificationRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.IdentificationResponse, _abc.Awaitable[_onyx_pb2.IdentificationResponse]]:
        """-------------------------------------------------------------------------
        GetIdentification returns information that can be used to identify a system
        """

    @_abc_1.abstractmethod
    def StartManualRecord(
        self,
        request: _onyx_pb2.StartManualRecordRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.StartManualRecordResponse, _abc.Awaitable[_onyx_pb2.StartManualRecordResponse]]:
        """StartManualRecord starts the manual recorder for timeseries data"""

    @_abc_1.abstractmethod
    def StopManualRecord(
        self,
        request: _onyx_pb2.StopManualRecordingRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.StopManualRecordingResponse, _abc.Awaitable[_onyx_pb2.StopManualRecordingResponse]]:
        """StopManualRecord stops the manual recorder"""

    @_abc_1.abstractmethod
    def ManualRecordStatus(
        self,
        request: _onyx_pb2.ManualRecordStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.ManualRecordStatusResponse, _abc.Awaitable[_onyx_pb2.ManualRecordStatusResponse]]:
        """GetRecordersStatus return the status of the manual recorder"""

    @_abc_1.abstractmethod
    def StartRecorders(
        self,
        request: _onyx_pb2.StartRecordersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.StartRecordersResponse, _abc.Awaitable[_onyx_pb2.StartRecordersResponse]]:
        """StartRecorders starts all the recorders recording to the given path"""

    @_abc_1.abstractmethod
    def StopRecorders(
        self,
        request: _onyx_pb2.StopRecordersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.StopRecordersResponse, _abc.Awaitable[_onyx_pb2.StopRecordersResponse]]:
        """StopRecorders stops all the recorders recording"""

    @_abc_1.abstractmethod
    def GetRecordersStatus(
        self,
        request: _onyx_pb2.GetRecordersStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.GetRecordersStatusResponse, _abc.Awaitable[_onyx_pb2.GetRecordersStatusResponse]]:
        """GetRecordersStatus return the status of the recorders"""

    @_abc_1.abstractmethod
    def GetModuleConfig(
        self,
        request: _onyx_pb2.GetModuleConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.GetModuleConfigResponse, _abc.Awaitable[_onyx_pb2.GetModuleConfigResponse]]:
        """GetModuleConfig returns the configuration of an available 
        module in the module registry
        """

    @_abc_1.abstractmethod
    def SetModuleConfig(
        self,
        request: _onyx_pb2.SetModuleConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.SetModuleConfigResponse, _abc.Awaitable[_onyx_pb2.SetModuleConfigResponse]]:
        """SetModuleConfig sets the configuration of a module"""

    @_abc_1.abstractmethod
    def ControlPlaylist(
        self,
        request: _onyx_pb2.ControlPlaylistRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.ControlPlaylistResponse, _abc.Awaitable[_onyx_pb2.ControlPlaylistResponse]]:
        """ControlPlaylist is used to control playlist replay"""

    @_abc_1.abstractmethod
    def GetPlaylistStatus(
        self,
        request: _onyx_pb2.GetPlaylistStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.GetPlaylistStatusResponse, _abc.Awaitable[_onyx_pb2.GetPlaylistStatusResponse]]:
        """GetPlaylistStatus returns the status of the playlist replay.
        The replay can include the list of recordings in the selected playlist.
        """

    @_abc_1.abstractmethod
    def GetSystemBackups(
        self,
        request: _common_pb2.GetSystemBackupsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_common_pb2.GetSystemBackupsResponse, _abc.Awaitable[_common_pb2.GetSystemBackupsResponse]]:
        """GetSystemBackups returns the systems local and portal backups"""

    @_abc_1.abstractmethod
    def DeleteBackup(
        self,
        request: _onyx_pb2.DeleteBackupRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.DeleteBackupResponse, _abc.Awaitable[_onyx_pb2.DeleteBackupResponse]]:
        """DeleteBackup deletes the chosen backup from the system"""

    @_abc_1.abstractmethod
    def DownloadBackup(
        self,
        request: _onyx_pb2.DownloadBackupRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.DownloadBackupResponse, _abc.Awaitable[_onyx_pb2.DownloadBackupResponse]]:
        """DownloadBackup returns content of a system backup"""

    @_abc_1.abstractmethod
    def ManualBackup(
        self,
        request: _onyx_pb2.ManualBackupRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.ManualBackupResponse, _abc.Awaitable[_onyx_pb2.ManualBackupResponse]]:
        """ManualBackup prompts the system to manually backup"""

    @_abc_1.abstractmethod
    def GetManualBackupStatus(
        self,
        request: _onyx_pb2.GetManualBackupStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.GetManualBackupStatusResponse, _abc.Awaitable[_onyx_pb2.GetManualBackupStatusResponse]]:
        """GetManualBackupStatus gets status of manual backup"""

    @_abc_1.abstractmethod
    def TriggerDataBaseStatsCleanup(
        self,
        request: _onyx_pb2.TriggerDataBaseStatsCleanupRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.TriggerDataBaseStatsCleanupResponse, _abc.Awaitable[_onyx_pb2.TriggerDataBaseStatsCleanupResponse]]:
        """TriggerDataBaseStatsCleanup triggers the cleanup of the database stats
        This normally runs on a schedule but calling this will trigger it to run
        """

    @_abc_1.abstractmethod
    def StreamDetections(
        self,
        request: _onyx_pb2.StreamDetectionsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_onyx_pb2.StreamDetectionsResponse], _abc.AsyncIterator[_onyx_pb2.StreamDetectionsResponse]]:
        """StreamDetections requests a stream of events from the server
        This publishes detected events to the stream as they arrive in
        the event store
        """

    @_abc_1.abstractmethod
    def GetTimeseriesSources(
        self,
        request: _onyx_pb2.GetTimeseriesSourcesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.GetTimeseriesSourcesResponse, _abc.Awaitable[_onyx_pb2.GetTimeseriesSourcesResponse]]:
        """GetTimeseriesSources returns the list of timeseries sources that are
        available for streaming with the GetTimeSeries service.
        """

    @_deprecated("""GetTimeseries streams timeseries data from the given source.\nDeprecated: Use StreamTimeseriesOut instead.""")
    @_abc_1.abstractmethod
    def GetTimeseries(
        self,
        request: _onyx_pb2.GetTimeseriesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_common_pb2.TimeseriesPacket], _abc.AsyncIterator[_common_pb2.TimeseriesPacket]]:
        """GetTimeseries streams timeseries data from the given source.
        Deprecated: Use StreamTimeseriesOut instead.
        """

    @_deprecated("""StreamTimeseries streams timeseries data from the given source.\nDeprecated: Use StreamTimeseriesOut instead.""")
    @_abc_1.abstractmethod
    def StreamTimeseries(
        self,
        request: _onyx_pb2.StreamTimeseriesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_common_pb2.TimeseriesPacket], _abc.AsyncIterator[_common_pb2.TimeseriesPacket]]:
        """StreamTimeseries streams timeseries data from the given source.
        Deprecated: Use StreamTimeseriesOut instead.
        """

    @_abc_1.abstractmethod
    def StreamTimeseriesOut(
        self,
        request: _onyx_pb2.StreamTimeseriesOutRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_onyx_pb2.StreamTimeseriesOutResponse], _abc.AsyncIterator[_onyx_pb2.StreamTimeseriesOutResponse]]:
        """Stream timeseries packets out from the given source."""

    @_abc_1.abstractmethod
    def StreamTimeseriesIn(
        self,
        request_iterator: _MaybeAsyncIterator[_onyx_pb2.StreamTimeseriesInRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.StreamTimeseriesInResponse, _abc.Awaitable[_onyx_pb2.StreamTimeseriesInResponse]]:
        """StreamTimeseriesIn streams timeseries data into the given sink."""

    @_abc_1.abstractmethod
    def GetFiberLength(
        self,
        request: _onyx_pb2.FiberLengthRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.FiberLengthResponse, _abc.Awaitable[_onyx_pb2.FiberLengthResponse]]:
        """GetFiberLength returns the length of the fiber for a given FiberNumber"""

    @_abc_1.abstractmethod
    def GetChainStatus(
        self,
        request: _onyx_pb2.ChainStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_onyx_pb2.ChainStatusResponse, _abc.Awaitable[_onyx_pb2.ChainStatusResponse]]:
        """GetChainStatus returns the name of the current chain and if it is unsaved"""

def add_OnyxServicer_to_server(servicer: OnyxServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
